# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nautilopy',
                'doc_host': 'https://20KUTS.github.io',
                'git_url': 'https://github.com/20KUTS/nautilopy',
                'lib_path': 'nautilopy'},
  'syms': {'nautilopy.core': {'nautilopy.core.foo': ('core.html#foo', 'nautilopy/core.py')}}}
